include: package:lint/strict.yaml

analyzer:
  errors:
    todo: info
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'

linter:
  rules:
    directives_ordering: false
    flutter_style_todos: true
    prefer_single_quotes: true