name: dpip
description: "Disaster Prevention Information Platform"
publish_to: 'none'
version: 3.0.007

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  autostarter: 0.0.2
  awesome_notifications: 0.10.1
  awesome_notifications_core: 0.10.1
  awesome_notifications_fcm: 0.10.1
  cached_network_image: ^3.4.1
  clipboard: 0.1.3
  collection: ^1.19.1
  dash_flags: ^0.1.1
  device_info_plus: ^11.4.0
  disable_battery_optimization:
    git:
      url: https://github.com/pvsvamsi/Disable-Battery-Optimizations.git
      ref: 414b781
  dynamic_system_colors: ^1.8.0
  firebase_core: ^3.13.0
  firebase_messaging: 15.2.5
  fl_chart: ^0.71.0
  flex_color_picker: ^3.7.0
  flutter:
    sdk: flutter
  flutter_background_service: 5.1.0
  flutter_background_service_android: 6.3.0
  flutter_background_service_ios: 5.0.3
  flutter_background_service_platform_interface: 5.1.2
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: 2.0.5
  flutter_markdown: ^0.7.7
  fluttertoast: 8.2.12
  freezed_annotation: ^3.0.0
  geolocator: ^14.0.0
  geolocator_android: ^5.0.1+1
  go_router: ^15.1.1
  http: ^1.3.0
  image_gallery_saver:
    git:
      url: https://github.com/knottx/image_gallery_saver.git
      ref: knottx-latest
  in_app_purchase: ^3.2.1
  in_app_update: 4.2.3
  intl: any
  json_annotation: 4.9.0
  maplibre_gl: 0.21.0
  material_symbols_icons: ^4.2815.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  simple_icons: ^14.6.1
  skeletonizer: ^2.0.0-pre
  talker_flutter: ^4.7.2
  timezone: ^0.10.0
  tutorial_coach_mark: ^1.3.0
  url_launcher: ^6.3.1

dependency_overrides:
  intl: 0.19.0

dev_dependencies:
  build_runner: 2.4.15
  flutter_test:
    sdk: flutter
  in_app_purchase_platform_interface: ^1.4.0
  json_serializable: 6.9.5
  lint: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/map/
  - assets/map/icons/
  - assets/DPIP.png
  - assets/ExpTech.png
  - assets/location.json
  - assets/notify_test.json
  - assets/time.json
  - assets/box.json
  